name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.

name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
    - uses: actions/checkout@v1
      
    - name: Install
    run: |
      npm install
      npm run docs:build
      
    - name: Build and Deploy
    - uses: JamesIves/github-pages-deploy-action@releases/v3
  
    with:
    ACCESS_TOKEN: ${{ secrets.deploy_website }}
    BRANCH: gh-pages # The branch the action should deploy to.
    FOLDER: docs/.vuepress/dist # The folder the action should deploy.
